---
- name: "Install Drush with global Composer"
  shell: "{{drush_composer_bin}} global require drush/drush:{{drush_composer_version}} --no-interaction --no-ansi"
  sudo_user: "{{ drush_composer_user }}"
- name: "Get global Composer user home direcotry path."
  shell: cat /etc/passwd | grep -Ew {{ drush_composer_user }} | cut -d":" -f6
  register: drush_composer_user_home
- set_fact:
    drush_complete_sh: "{{ drush_composer_user_home.stdout }}/.composer/vendor/bin/drush.complete.sh"
