
sudo: required
dist: trusty

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
 # Install Ansible.
  - sudo pip install ansible==1.9.4

before_script:

script:
   - ls -la
   - sudo ansible-playbook -vvvv services/jenkinsbox.yml -i 'localhost,' --connection=local --extra-vars="server_ip=127.0.0.1 mysql_root_password="
