---
drupal_user: admin
drupal_pass: propeople
update_admin_user: true
installation_profile_name: pp
mysql_user: root
mysql_pass: root
mysql_db: drupal
cache_folder: /var/www/cache
backup_folder: /var/www/backup
php_env_vars: 'APP_ENV=dev' # APP_ENV=dev - this varible will be set at PR_BUILDER from CI shell executor.
site_url: 'http://drupal.192.168.56.132.xip.io/'
# Site url to download assets via stage_file_proxy.
origin_site_url: 'http://192.168.56.132.xip.io/'
# This variable will be used for variable_get('environment'). Can be overridden by CI server.
# development = 'default', demo = 'demo', staging = 'staging', production = 'production'.
pp_environment: 'default'
# This variable allows select type of installation. Can be overridden by CI server.
# From installation profile = 'profile', from sql dump = 'sql'.
workflow_type: 'profile'
# This variable allows make backup before processing. Can be overridden by CI server.
# true, false.
make_backup: false
# htpasswd protection for securing backups.
backup_user: propeople
backup_pass: givemebackup
is_windows: false
source_backup_name: latest_dev.sql.gz
# URL to the source database. Can be overridden by CI server.
source_database: http://{{ backup_user }}:{{ backup_pass }}@192.168.56.132/backup/{{ source_backup_name }}
