---
env:
  pre_settings: []
  modules:
    - { name: 'dblog', status: true }
    - { name: 'stage_file_proxy', status: true }
    - { name: 'devel', status: true }
    - { name: 'views_ui', status: true }
    - { name: 'diff', status: true }
  drush_commands:
    # Update admin username and password.
    - { name: 'sqlq', status: true, arguments: "\"UPDATE users SET name='{{ drupal_user }}' WHERE uid=1\"" }
    - { name: 'user-password', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
  post_settings:
    - { name: '$conf["stage_file_proxy_origin"]', status: true, value: "{{ origin_site_url }}" }
    - { name: '$conf["error_level"]', status: true, value: '2' }
    - { name: '$conf["cache"]', status: true, value: '0' }
    - { name: '$conf["block_cache"]', status: true, value: '0' }
    - { name: '$conf["preprocess_css"]', status: true, value: '0' }
    - { name: '$conf["preprocess_js"]', status: true, value: '0' }