---
env:
  pre_settings: []
  modules: []
    - { name: 'dblog', status: true }
    - { name: 'stage_file_proxy', status: true }
    - { name: 'devel', status: true }
    - { name: 'views_ui', status: true }
    - { name: 'diff', status: true }
  drush_commands: []
    - { name: 'search-api-clear', status: false, arguments: "-l {{ site_url }}" }
    - { name: 'search-api-index ', status: false, arguments: "-l {{ site_url }}" }
    - { name: 'solr-mark-all', status: false, arguments: "-l {{ site_url }}" }
    - { name: 'solr-index ', status: false, arguments: "-l {{ site_url }}" }
  post_settings:
    - { name: '$conf["stage_file_proxy_origin"]', status: true, value: "{{ origin_site_url }}" }
    - { name: '$conf["error_level"]', status: true, value: '0' }
