---

- name: Was composer downloaded
  sudo: yes
  stat: path={{ composer_dir }}
  register: is_composer_dir

- name: Install apt repos
  apt_repository: repo={{ item }}
  with_items: sniffers_apt_repos
  when: is_composer_dir.stat.exists == false
  tags:
    - nodejs

- name: Update apt cache
  sudo: yes
  apt: update_cache=yes
  ignore_errors: yes

- name: Install apt packages
  apt: name={{ item }} state=present
  with_items: sniffers_apt_packages
  when: is_composer_dir.stat.exists == false
  tags:
    - sniffers
    - composer
    - git

- name: Prepare directory for global composer libs
  sudo: yes
  file: path={{ composer_dir }} state=directory
  when: is_composer_dir.stat.exists == false
  tags:
    - sniffers

- name: Install composer global requires
  sudo: yes
  shell: "cd {{ composer_dir }} && composer require --prefer-dist {{ item.package }}{{ item.version }}"
  with_items: composer_global_require
  when: is_composer_dir.stat.exists == false
  tags:
    - sniffers
    - composer
    - git

- name: Install global git repos
  sudo: yes
  git: repo={{ item.repo }} dest={{ composer_dir }}/vendor/podarok/{{ item.name }} version={{ item.branch }}
  with_items: git_repos
  when: is_composer_dir.stat.exists == false
  #ignore_errors: yes
  tags:
    - sniffers
    - git

- name: Install php codesniffer standards
  sudo: yes
  file: src={{ composer_dir }}/{{ item.path }} dest={{ composer_dir }}/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/{{ item.name }} state=link
  with_items: phpcs_standards
  when: is_composer_dir.stat.exists == false
  tags:
    - sniffers
    - git

- name: Fix permissions for composer libs
  sudo: yes
  file: path={{ composer_dir }} state=directory mode=0655 recurse=yes
  when: is_composer_dir.stat.exists == false

- name: Create symlink to PATH
  sudo: yes
  file: src={{ composer_dir }}/vendor/bin/phpcs dest={{ phpcs_bin }} state=link mode=0655 force=yes
  when: is_composer_dir.stat.exists == false

- name: Install nodejs packages
  npm: name={{ item }} global=yes
  with_items: npm_packages
  when: is_composer_dir.stat.exists == false

- name: Update ruby alternatives for using ruby 1.9.1(3) version
  sudo: yes
  when: is_composer_dir.stat.exists == false
  shell: "update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400 --slave /usr/share/man/man1/ruby.1.gz ruby.1.gz /usr/share/man/man1/ruby1.9.1.1.gz --slave /usr/bin/ri ri /usr/bin/ri1.9.1 --slave /usr/bin/irb irb /usr/bin/irb1.9.1 --slave /usr/bin/rdoc rdoc /usr/bin/rdoc1.9.1"
  tags:
    - sniffers
    - ruby

- name: Install gem packages
  shell: "gem install {{ item }}"
  with_items: gem_packages
  ignore_errors: yes
  when: is_composer_dir.stat.exists == false
  tags:
    - sniffers
    - gem
    - ruby
