---
- name: Getting name for settings (WINDOWS)
  set_fact: settings_file=/tmp/reinstall_settings.php
  when: is_windows == true

- name: Getting name for settings (UNIX)
  set_fact: settings_file=sites/default/settings.php
  when: is_windows == false

- name: Remove settings.php
  file: name={{ settings_file }} state=absent
  sudo: yes

- name: Creating settings.php
  sudo: yes
  shell: "cp sites/default/default.settings.php {{ settings_file }}"

- name: Adding database variable to settings.php
  sudo: yes
  lineinfile: dest='{{ settings_file }}' line='$databases = array(\"default\" => array (\"default\" => array (\"database\" => \"{{ mysql_db }}\", \"username\" => \"{{ mysql_user }}\", \"password\" => \"{{ mysql_pass }}\", \"host\" => \"127.0.0.1\", \"port\" => \"\", \"driver\" => \"mysql\", \"prefix\" => \"\", ), ), );'

- name: Add general pre-settings to settings.php
  lineinfile: dest='{{ settings_file }}' line='{{ item.name }} = \"{{ item.value }}\";'
  when: item.status == true
  with_items: global_env.pre_settings

- name: Add environment specific pre-settings
  lineinfile: dest='{{ settings_file }}' line='{{ item.name }} = \"{{ item.value }}\";'
  when: item.status == true
  with_items: env.pre_settings

- name: Copy settings back (WINDOWS)
  shell: cp {{ settings_file }} sites/default/settings.php
  when: is_windows == true
