---
placeholder: 'placeholder'

# We are using unix pam autentification module for jenkins.
plugins:
  - 'http://mirrors.jenkins-ci.org/plugins/ansicolor/0.4.1/ansicolor.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/token-macro/1.10/token-macro.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/ssh-agent/1.3/ssh-agent.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/plain-credentials/1.1/plain-credentials.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/credentials/1.22/credentials.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/git-client/1.18.0/git-client.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/git/2.4.0/git.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/github-api/1.69/github-api.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/github/1.12.1/github.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/ghprb/1.15-0/ghprb.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/htmlpublisher/1.5/htmlpublisher.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/jquery/1.11.2-0/jquery.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/matrix-auth/1.2/matrix-auth.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/matrix-project/1.6/matrix-project.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/project-description-setter/1.1/project-description-setter.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/ssh-credentials/1.11/ssh-credentials.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/hipchat/0.1.9/hipchat.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/scm-api/0.2/scm-api.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/scripttrigger/0.31/scripttrigger.hpi'
  - 'http://mirrors.jenkins-ci.org/plugins/parameterized-trigger/2.28/parameterized-trigger.hpi'

jenkins_pkg_version: 'http://pkg.jenkins-ci.org/debian/binary/jenkins_1.624_all.deb'

# Delay before jenkins up and running. Sometimes it is not enouph.
startup_delay_s: 40

jenkins_jobs:
  - { name: 'BACKUP_PROD_DB', template: 'backup_prod_db.xml.j2' }
  - { name: 'DEMO', template: 'demo.xml.j2' }
  - { name: 'DISK_USAGE_TRIGGER', template: 'disk_usage_trigger.xml.j2' }
  # @todo project_name should be reqired variable. We should have layer of cibox-wide required variables.
  - { name: '{{ project_name }}_PR_BUILDER', template: 'pr_builder.xml.j2' }
  - { name: 'SERVER_CLEANER', template: 'server_cleaner.xml.j2' }
