---

- name: Install apt keys for Google Chrome
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  tags: behat-selenium

- name: WHAT IS IT? o_O
  shell: sh -c 'echo deb http://dl.google.com/linux/chrome/deb/ stable main > /etc/apt/sources.list.d/google.list'
  tags: behat-selenium

- name: Install dependencies
  sudo: yes
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=installed update-cache=yes"
  with_items: behat_selenium2_dependencies
  tags: behat-selenium

- include: chrome.yml

- include: selenium.yml

- name: Create xvfb startup script
  template: src=xvfb.j2 dest=/etc/init.d/xvfb  mode=0750
  tags: behat-selenium

- name: Enable xvfb on boot
  sudo: yes
  shell: update-rc.d xvfb defaults
  tags: behat-selenium
