---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.132
            forwarded_port:
                CocLsFE7aIwA:
                    host: '8080'
                    guest: '80'
                CocLsFE7aIwE:
                    host: '8083'
                    guest: '3306'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            8Q9vTs08YuK2:
                source: ./
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
        - htop
        - git
        - php5-memcache
        - unzip
        - libaugeas-dev
    dot_files:
        - bash_aliases: null
    _prevent_empty: ''
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        EYZeANveIIwp:
            servername: drupal.192.168.56.132.xip.io
            docroot: /var/www/drupal
            port: '80'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        TQX65dxNZL1b:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    install: '1'
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - memcached
            - PDO
            - PDO_MYSQL
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        max_execution_time: '300'
        memory_limit: 1024M
        post_max_size: 64M
        upload_max_filesize: 64M
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: '1'
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: root
    phpmyadmin: 0
    adminer: '1'
    bind-address: '0.0.0.0'
    databases:
        nL5g8yIVTFjA:
            grant:
                - ALL
            name: drupal
            host: localhost
            user: drupal
            password: drupal
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'

solr:
    config_path: "/var/www/docroot/sites/all/modules/contrib/apachesolr/solr-conf/solr-4.x/"


